celeb_dict={
"71":"Katy Perry",
"64":"Justin Bieber",
"60":"Barack Obama",
"59":"Taylor Swift",
"47":"Lady Gaga",
"47":"Rihanna",
"46":"Justin Timberlake",
"44":"Ellen De Generes",
"42":"Britney Spears",
"36":"Cristiano Ronaldo",
"32":"Kim Kardashian West",
"32":"Jennifer Lopez",
"32":"Shakira",
"30":"Selena Gomez",
"29":"Ariana Grande",
"28":"Demi Lovato",
"28":"Oprah Winfrey",
"26":"P!nk",
"26":"Jimmy Fallon",
"24":"Harry Styles",
"23":"One Direction",
"23":"Drake",
"23":"Lil Wayne",
"23":"Kaka",
"22":"Adele",
"22":"Bill Gates",
"22":"Niall Horan",
"22":"Alicia Keys",
"22":"LeBron James",
"21":"Bruno Mars",
"20":"Pitbull",
"20":"Liam Payne",
"20":"Wiz Khalifa",
"20":"Miley Cyrus",
"19":"Louis Tomlinson",
"19":"Kevin Hart",
"19":"Marshall Mathers",
"19":"Nicki Minaj",
"19":"Avril Lavigne",
"18":"Neymar",
"18":"Emma Watson",
"17":"David Guetta",
"17":"Daniel Tosh",
"17":"Ashton Kutcher",
"17":"Conan O'Brien",
"16":"Niel Patrick Harris",
"15":"Mariah Carey",
"15":"Amitabh Bachchan",
"15":"Coldplay",
"14":"Christina Aguilera",
"14":"Kourtney Kardashian",
"14":"Zayn Malik",
"14":"Jim Carrey",
"14":"Khloe Kardashian",
"14":"Chris Brown",
"14":"Beyoncé Knowles",
"14":"Ed Sheeran",
"13":"Ryan Seacrest",
"13":"Shah Rukh Khan",
"13":"Paris Hilton",
"13":"Agnes Monica",
"13":"Will.I.Am",
"13":"Ivete Sangalo",
"13":"Aamir Khan",
"13":"Leonardo DiCaprio",
"13":"Narendra Modi",
"12":"Ashley Tisdale",
"12":"Kanye West",
"12":"Tyra Banks",
"12":"Alejandro Sanz",
"12":"Blake Shelton",
"12":"Salman Khan",
"12":"Snoop Dogg",
"12":"Ronaldinho Gaucho",
"12":"Ricky Martin",
"12":"Simon Cowell",
"12":"Mohamad Alarefe",
"11":"Charlie Sheen",
"11":"Claudia Leitte",
"11":"Dalai Lama",
"11":"Maroon 5",
"11":"Kendall Jenner",
"11":"Andrés Iniesta",
"10":"Carly Rae Jepsen",
"10":"Zac Efron",
"10":"Marcos Mion",
"10":"Luciano Huck",
"10":"Gerard Piqué",
"10":"Raditya Dika",
"10":"Deepika Padukone ",
"10":"Juanes",
"10":"Sean Combs",
"10":"Kevin Durant",
"10":"Ludacris",
"10":"Ahmad Mazin Alshugairi",
"10":"Paulina Rubio",
"10":"Danilo Gentili",
"10":"Kelly Clarkson",
"10":"Usher",
"10":"Paulo Coelho"
}
